# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default='Please add your content here')),
                ('modified_content', models.TextField(default='Please add your content here')),
                ('is_basic', models.BooleanField(default=False)),
                ('is_first', models.BooleanField(default=False)),
                ('main_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_main_requirement', to='app.Topic')),
                ('requirement_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_requirement_for', to='app.Topic')),
                ('requirements', models.ManyToManyField(blank=True, related_name='_topic_requirements_+', through='app.Requirement_Relation', to='app.Topic')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='requirement_relation',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_topic', to='app.Topic'),
        ),
        migrations.AddField(
            model_name='requirement_relation',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_topic', to='app.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='requirement_relation',
            unique_together=set([('topic', 'requirement')]),
        ),
    ]
